# Generated by Django 5.0.6 on 2025-01-07 21:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_end_datetime_alter_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_code',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
