# Generated by Django 5.0.6 on 2025-01-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_admin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('MAYBE', 'Maybe'), ('WAITING_LIST', 'Waiting list')], default='Invited', max_length=20, verbose_name='Status'),
        ),
    ]
